[package]
name = "intermix"
version = "0.1.0"
authors = ["Andy Hartford <hartforda@gmail.com>"]

[dependencies]
ioctl-rs = "0.1.3"
libc = "0.1.10"
log = "0.3"
log4rs = "0.3.3"
num = "0.1.27"
pty = "0.1"
term = "0.2.12"
termios = "0.2"
tsm-sys = "0.1"
