refresh_rate = 30

[appender.root]
kind = "file"
path = "log/intermix.log"
pattern = "%d %l - %m (%f)"

[appender.client]
kind = "file"
path = "log/client.log"

[appender.server]
kind = "file"
path = "log/server.log"

[root]
appenders = ["root"]
level = "trace"

[[logger]]
additive = false
appenders = ["client"]
level = "trace"
name = "intermix::client"

[[logger]]
additive = false
appenders = ["server"]
level = "trace"
name = "intermix::server"
