refresh_rate = 30

[appender.root]
kind = "file"
path = "log/intermix.log"
pattern = "%d - %m"

[appender.program]
kind = "file"
path = "log/program.log"
pattern = "%d - %m"

[appender.window]
kind = "file"
path = "log/window.log"
pattern = "%d - %m"

[appender.pane]
kind = "file"
path = "log/pane.log"
pattern = "%d - %m"

[appender.tty_painter]
kind = "file"
path = "log/tty_painter.log"
pattern = "%d - %m"

[root]
appenders = ["root"]
level = "trace"

[[logger]]
additive = false
appenders = ["program"]
level = "trace"
name = "intermix::program"

[[logger]]
additive = false
appenders = ["window"]
level = "trace"
name = "intermix::window"

[[logger]]
additive = false
appenders = ["pane"]
level = "trace"
name = "intermix::pane"

[[logger]]
additive = false
appenders = ["tty_painter"]
level = "trace"
name = "intermix::tty_painter"
