refresh_rate = 30

[appender.root]
kind = "file"
path = "log/intermix.log"
pattern = "%d %f:%L\t%l - %m"

[appender.client]
kind = "file"
path = "log/client.log"
pattern = "%d %f:%L\t%l - %m"

[appender.server]
kind = "file"
path = "log/server.log"
pattern = "%d %f:%L\t%l - %m"

[root]
appenders = ["root"]
level = "trace"

[[logger]]
additive = false
appenders = ["client"]
level = "trace"
name = "intermix::client"

[[logger]]
additive = false
appenders = ["server"]
level = "trace"
name = "intermix::server"
